version: '2'
services:
  mysql:
    image: mysql:5.6
    container_name: mysql_server
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 13122002
      MYSQL_DATABASE: medusa
      MYSQL_USER: kandev
      MYSQL_PASSWORD: 13122002
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal

  game-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: game_server
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: medusa
      DB_USER: kandev
      DB_PASSWORD: 1312200
    ports:
      - "14445:14445"  # Cổng game bạn cần
    volumes:
      - ./data:/app/data
      - ./restart_game.sh:/app/restart_game.sh
    networks:
      - internal
volumes:
  mysql_data:

networks:
  internal:
    driver: bridge