version: "3.9"

services:
  db:
    image: mysql:5.7
    container_name: mysql57_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nro_medusa
      MYSQL_USER: kandev
      MYSQL_PASSWORD: 13122002
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./update_sql/medusa_backup.sql:/docker-entrypoint-initdb.d/backup.sql:ro
    command: --default-authentication-plugin=mysql_native_password

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nro_rise
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: nro_medusa
      DB_USER: kandev
      DB_PASS: 13122002
    ports:
      - "14445:14445"
    volumes:
      - ./data:/app/data
      - ./lib:/app/lib