-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.6.23 - MySQL Community Server (GPL)
-- Server OS:                    Win64
-- HeidiSQL Version:             12.1.0.6537
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dumping database structure for medusa
CREATE DATABASE IF NOT EXISTS `medusa` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `medusa`;

-- Dumping structure for table medusa.item_option_template
CREATE TABLE IF NOT EXISTS `item_option_template` (
  `id` int(11) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

-- Dumping data for table medusa.item_option_template: ~258 rows (approximately)
DELETE FROM `item_option_template`;
INSERT INTO `item_option_template` (`id`, `NAME`) VALUES
	(0, 'Tấn công+#'),
	(1, 'Thời gian sử dụng # phút'),
	(2, 'HP, KI+#000'),
	(3, 'Vô hiệu và biến #% sát thương chưởng thành KI'),
	(4, 'Hồi phục #% KI khi bị đánh'),
	(5, '+#% sức đánh chí mạng'),
	(6, 'HP+#'),
	(7, 'KI+#'),
	(8, 'Hút #% HP, KI xung quanh mỗi 5 giây'),
	(9, 'Hiệu lực trong # phút'),
	(10, 'Chính xác: +#'),
	(11, 'Công đức +#'),
	(12, 'Số lần sử dụng còn lại +#'),
	(13, 'Số yêu quái đã hạ +#'),
	(14, 'Chí mạng+#%'),
	(15, 'Phản đòn cận chiến+#'),
	(16, 'Tốc độ di chuyển+#%'),
	(17, 'Né đòn: +#'),
	(18, 'Chính xác: +#%'),
	(19, 'Tấn công+#% khi đánh quái'),
	(20, 'PIN #'),
	(21, 'Yêu cầu sức mạnh # tỉ'),
	(22, 'HP+#K'),
	(23, 'KI+#K'),
	(24, 'Làm tăng trọng lực, gây chậm mọi người xung quanh'),
	(25, 'Tàng hình mỗi 5 giây'),
	(26, 'Hóa đá mọi người xung quanh mỗi 30 giây'),
	(27, '+# HP/30s'),
	(28, '+# KI/30s'),
	(29, 'Biến Sôcôla mọi người xung quanh mỗi 30 giây'),
	(30, 'Không thể giao dịch'),
	(31, 'Số lượng #'),
	(32, 'Không bị hóa Xương'),
	(33, 'Dịch chuyển tức thời'),
	(34, 'Tinh ấn'),
	(35, 'Nguyệt ấn'),
	(36, 'Nhật ấn'),
	(37, 'Số lần đã ký gửi #'),
	(38, 'Chỉ có tác dụng khi hợp thể'),
	(39, '<Cập nhật bản mới để xem>'),
	(40, 'Siêu cải trang # đá ngũ sắc'),
	(41, '(+16)'),
	(42, '(+16)'),
	(43, '(+16)'),
	(44, '(+16)'),
	(45, '(+16)'),
	(46, '(+16)'),
	(47, 'Giáp+#'),
	(48, 'HP, KI+#'),
	(49, 'Sức đánh SSS +#%'),
	(50, 'Sức đánh+#%'),
	(51, 'Sôn Gô Ku ss#'),
	(52, 'Ca Đic siêu ss#'),
	(53, 'Broly'),
	(54, 'Mr. Santa'),
	(55, 'Broly ss#'),
	(56, 'Ca Lích'),
	(57, 'Thên Xin Hăng'),
	(58, 'Pic'),
	(59, 'Siêu na mếc #'),
	(60, 'Sôn Gô Tên'),
	(61, 'Sôn Gô Ku'),
	(62, 'Phục hồi thể lực #%'),
	(63, 'Còn lại # ngày'),
	(64, 'Còn lại # giờ'),
	(65, 'Còn lại # phút'),
	(66, 'Chưa có'),
	(67, 'Dùng nâng cấp găng tay'),
	(68, 'Dùng để nâng cấp áo'),
	(69, 'Dùng để nâng cấp quần'),
	(70, 'Dùng để nâng cấp giày'),
	(71, 'Dùng để nâng cấp rađa'),
	(72, 'Cấp #'),
	(73, ''),
	(74, 'Dùng để ép thành đá'),
	(75, 'Dùng để làm phép'),
	(76, 'Vip'),
	(77, 'HP+#%'),
	(78, 'Sức hủy diệt+#%'),
	(79, 'Đệ tử #% sức đánh'),
	(80, 'HP+#%/30s'),
	(81, 'KI+#%/30s'),
	(82, 'Không bị quái chủ động đánh và giảm 20% sát thương khi bị đánh'),
	(83, 'Tăng 20% sức mạnh và tiềm năng nhận được khi đánh quái'),
	(84, 'Dùng để bay không tốn KI'),
	(85, 'Dùng để bay và phục hồi KI'),
	(86, 'Ký gửi vàng'),
	(87, 'Ký gửi ngọc'),
	(88, 'Cộng #% exp khi đánh quái'),
	(89, 'Dùng để bay và phục hồi HP, KI'),
	(90, 'Tặng cho người khác (bỏ ra đất) sẽ được nhận may mắn'),
	(91, 'Mở ra để nhận may mắn'),
	(92, 'Chúc tết bang hội và mọi người kèm theo pháo hoa'),
	(93, 'HSD # ngày'),
	(94, 'Giáp #%'),
	(95, 'Biến #% tấn công thành HP'),
	(96, 'Biến #% tấn công thành KI'),
	(97, 'Phản #% sát thương'),
	(98, 'Xuyên giáp #% chưởng'),
	(99, 'Xuyên giáp #% cận chiến'),
	(100, '+#% vàng từ quái'),
	(101, '+#% TN,SM'),
	(102, '# Sao Pha Lê'),
	(103, 'KI +#%'),
	(104, 'Biến #% tấn công quái thành HP'),
	(105, 'Vô hình khi không đánh quái và boss'),
	(106, 'Không ảnh hưởng bởi cái lạnh'),
	(107, '# Sao Pha Lê (Chưa ép)'),
	(108, '#% Né đòn'),
	(109, 'Hôi, giảm #% HP'),
	(110, 'Dò pha lê'),
	(111, 'Phân tâm'),
	(112, 'Giảm #% khi mua Avatar hoặc Cải trang'),
	(113, 'Ném cho Sói Hẹc Quyn'),
	(114, '+#% TĐ chạy'),
	(115, 'Biến cà rốt'),
	(116, 'Kháng TDHS'),
	(117, 'Đẹp +#% SĐ cho mình và người xung quanh'),
	(118, 'Tới ngay mục tiêu và gây choáng trong # mili giây'),
	(119, 'Gây mù xung quanh trong # giây'),
	(120, 'Ra đòn sau # giây'),
	(121, 'Ru ngủ trong # giây'),
	(122, 'Bảo vệ trong # giây'),
	(123, 'Trói gô mục tiêu trong # giây'),
	(124, 'Tỉnh giấc bị yếu đi -#% sức đánh trong 10 giây'),
	(125, 'Tăng và hồi phục #% HP tạm thời cho mình và xung quanh trong 30 giây'),
	(126, 'Biến sôcôla làm yếu đi -#% sức đánh trong 30 giây'),
	(127, 'Set Winther Kaioken'),
	(128, 'Set Winther Kirin'),
	(129, 'Set Winther Sôngôku'),
	(130, 'Set Winther Picolo'),
	(131, 'Set Winther Ốc tiêu'),
	(132, 'Set Winther Pikkoro Daimao'),
	(133, 'Set Winther Kakarot'),
	(134, 'Set Winther Ca Đíc'),
	(135, 'Set Winther Nappa'),
	(136, '$(5 món +100% sát thương đấm Galick)'),
	(137, '$(5 món x5 thời gian hóa khỉ)'),
	(138, '$(5 món +100% HP)'),
	(139, '$(5 món x2 sát thương Kaioken)'),
	(140, '$(5 món +100% sát thương Quả Cầu Kênh Khi)'),
	(141, '$(5 món 100% sát thương Kamejoko)'),
	(142, '$(5 món +200% KI)'),
	(143, '$(5 món 100% sát thương Liên hoàn)'),
	(144, '$(5 món +100% sát thương Đẻ Trứng)'),
	(145, '$(Ở gần 1 CT Dr Slum khác loại +20% sức đánh +66% tốc độ chạy)'),
	(146, '$(Ở gần 2 CT Dr Slum khác loại +30% sức đánh +100% tốc độ chạy)'),
	(147, '+#% sức đánh'),
	(148, '+#% tốc độ chạy'),
	(149, '(Chỉ số tăng khi ở gần CT Hải Tặc khác loại)'),
	(150, '(Chỉ số tăng khi ở gần Android Sát Thủ khác loại)'),
	(151, '$(Ở gần 1 CT nhóm Piláp khác loại +20% sức đánh +66% tốc độ chạy)'),
	(152, '$(Ở gần 2 CT nhóm Piláp khác loại +30% sức đánh +100% tốc độ chạy)'),
	(153, '#% tỉ lệ phát nổ sau khi chết'),
	(154, 'Không thể bán lại cho người khác'),
	(155, 'Giảm 50% sức đánh, HP, KI và +#% SM, TN, vàng từ quái'),
	(156, 'Cộng dồn 1% sức đánh khi chỉ dùng chiêu đấm, tối đa #%'),
	(157, 'Giảm #% mọi sát thương khi KI dưới 20%'),
	(158, 'Khi ở trần và không đeo cải trang sẽ có cơ hội tìm thấy vật phẩm sự kiện'),
	(159, 'x# sức đánh đòn cận chiến và đòn chưởng cơ bản mỗi phút'),
	(160, '+#% TN, SM cho đệ tử khi sư phụ mặc cải trang này'),
	(161, 'Thêm # ngọc mỗi ngày khi đánh quái.'),
	(162, 'Cute hồi #% KI/s bản thân và xung quanh'),
	(163, 'Biến người xung quanh thành Bí Ngô'),
	(164, 'Đổi bằng # điểm sự kiện'),
	(165, 'Cơ hội ra đòn +#% sát thương lửa khi cận chiến quái'),
	(166, 'Ngầu +#% sức đánh lên quái khi bay với Cải Trang Tàu Pảy Pảy'),
	(167, 'Tạo không khí lạnh'),
	(168, 'Hấp thụ sức mạnh rồi bộc phá'),
	(169, 'Cơ hội hạ độc đối thủ'),
	(170, 'Ngầu +#% sức đánh lên quái khi bay với Cải Trang nhà Fide'),
	(171, 'Số lượng #K'),
	(172, '#'),
	(173, 'Phục hồi #% HP và KI cho đồng đội'),
	(174, 'Sự kiện năm #'),
	(175, 'Giảm #% thời gian bị mù'),
	(176, '$(Ở gần đủ 5 loại +20% sức đánh +50% tốc độ chạy)'),
	(177, '$(Tối đa +2% tất cả khi ở gần Mabư mập)'),
	(178, 'KI+#%/10s'),
	(179, '+2% sức đánh, tối đa 10% khi ở gần Cải Trang tộc Demons Frost'),
	(180, '+#% sức đánh khi ở gần Cải Trang Black Gohan Rose'),
	(181, 'Dịch chuyển tức thời +#% sát thương'),
	(182, '+#% sát thương đệ từ trứng'),
	(183, 'Giảm #% thời gian hồi Khiên'),
	(184, '+#% sức đánh, tối đa 10% khi ở gần Gohan xanh, Poc đỏ, Arale búp bê'),
	(185, '+# giờ sử dụng'),
	(186, 'Biến mọi người xung quanh thành kẹo mỗi 30 giây'),
	(187, 'Giảm # giây thời gian bị mù'),
	(188, 'Option'),
	(189, 'Set Nhân Hoàng'),
	(190, 'Set Ma Thần'),
	(191, 'Set Thiên Tử'),
	(192, 'SET Winther '),
	(193, '$(Tăng 10%HP,KI và 10% sức đánh chí mạng khi mặc 2 món Winther )'),
	(194, 'HP Pháp sư +#%'),
	(195, 'KI Pháp sư +#%'),
	(196, 'Sức đánh Pháp sư +#%'),
	(197, 'Sức đánh Chí mạng Pháp sư +#%'),
	(198, 'Đã pháp sư hóa # lần'),
	(199, '$(5 món tăng 250% Sát thương Chí mạng, +40% Sức đánh, +450% kamejoko và +650% Kaioken)'),
	(200, '$(5 món tăng 250% sát thương Chí mạng, +30% Sức đánh, +1500% KI , +750% sát thương Masenko và +550% sát thương Liên Hoàn)'),
	(201, '$(5 món tăng 250% sát thương Chí mạng, + 35% Sức đánh, +800% HP, +750% sát thương Galick và 600% Antomic )'),
	(202, '1000% ST Liên hoàn'),
	(203, '1200% ST Galick'),
	(204, 'Ấn Nguyên Thủy'),
	(205, 'Ấn Ma Hóa'),
	(206, 'Ấn Thần Hóa'),
	(207, 'Cải Trang Sự Kiện'),
	(208, 'Đồ rơi từ Quái'),
	(209, 'Đồ rơi từ Boss'),
	(210, 'Set Sên Winther '),
	(211, 'Có thể giao dịch'),
	(212, 'Ấn Hư Vô'),
	(213, 'SET Nguyên Thủy TD'),
	(214, 'SET Nguyên Thủy NM'),
	(215, 'SET Nguyên Thủy XD'),
	(216, '$(5 món  +5000% Sức đánh,10.000% Sát thương Chí mạng, 100K SDG, 6000% Kaioken, 5000% Kamejoko)'),
	(217, '$(5 món  +5000% Sức đánh, 10.000% Sát thương Chí mạng, 100K SDG, 5000% Liên Hoàn, 7000% Masenko)'),
	(218, '$(5 món  +5000% Sức đánh, 10.000% Sát thương Chí mạng, 100K SDG, 5000% Galick, 10.000% Antomic)'),
	(219, 'Sức Đánh Bóng Tối +#%'),
	(220, 'Sát thương chí mạng bóng tối +#%'),
	(221, 'HP bóng tối +#%'),
	(222, 'KI bóng tối +#%'),
	(223, 'Đã bóng tối hóa # lần'),
	(224, 'SET THỐNG KHỔ TRÁI ĐẤT'),
	(225, 'SET THỐNG KHỔ NAMEC'),
	(226, 'SET THỐNG KHỔ XAYDA'),
	(227, '$(5 món  +500K% Sức đánh,100K% Sát thương Chí mạng,500K% Kamejoko)'),
	(228, '$(5 món  +500K% Sức đánh, 100K% Sát thương Chí mạng, 500K% Liên Hoàn)'),
	(229, '$(5 món  +500K% Sức đánh, 100K% Sát thương Chí mạng,  500K% Galick)'),
	(230, 'Ngọc Rồng Winther '),
	(231, 'Thuộc Hạ Kaido'),
	(232, 'Sức Đánh Ánh Sáng +#%'),
	(233, 'Sát thương chí mạng ánh sáng +#%'),
	(234, 'Hạn sử dụng # ngày (Không thể gia hạn)'),
	(235, 'Set Jiren TD'),
	(236, 'Set Jiren NM'),
	(237, 'Set Jiren XD'),
	(238, '$(5 món  +1M% Sức đánh, 200K% Sát thương Chí mạng, 1M% Kamejoko)'),
	(239, '$(5 món  +1M% Sức đánh, 200K% Sát thương Chí mạng, 1M% Liên Hoàn)'),
	(240, '$(5 món  +1M% Sức đánh, 200K% Sát thương Chí mạng,  +1M% Galick)'),
	(241, 'Set Goku Ultra Instinct TD'),
	(242, 'Set Goku Ultra Instinct NM'),
	(243, 'Set Goku Ultra Instinct XD'),
	(244, '$(5 món  +2M% Sức đánh, 300K% Sát thương Chí mạng, 2M% Kamejoko, 60% Né Đòn Chuẩn)'),
	(245, '$(5 món  +2M% Sức đánh, 300K% Sát thương Chí mạng, 2M% Liên Hoàn, 60% Né Đòn Chuẩn)'),
	(246, '$(5 món  +2M% Sức đánh, 300K% Sát thương Chí mạng,  2M% Galick, 60% Né Đòn Chuẩn)'),
	(247, '$(Phụ Kiện Kích Hoạt Winther )'),
	(248, 'Phụ Kiện Kích Hoạt Winther \r\n(2 món + 1M % SĐ, HP, MP, GIÁP)'),
	(249, 'Phụ Kiện Kích Hoạt Winther \r\n(3 món + 2M % SĐ, HP, MP, GIÁP)'),
	(250, 'Phụ Kiện Kích Hoạt Winther \r\n(5 món + 5M % SĐ, HP, MP, GIÁP)'),
	(251, 'HP Ánh Sáng +#%'),
	(252, 'KI Ánh Sáng +#%'),
	(253, 'Đã ánh sáng hóa # lần'),
	(254, 'Tiên Khí'),
	(255, 'Thánh Khí'),
	(256, 'Thần Khí'),
	(257, 'Tiên Lực +#');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
